name: Update README
on:
  schedule:
    - cron: "* 23 * * 1"
  workflow_dispatch:
jobs:
  build:
    name: Update the README with my recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: AdamJ
          COMMIT_EMAIL: adam.jolicoeur@protonmail.com
          COMMIT_MSG: "Latest activity added to README"
          MAX_LINES: 5
          EMPTY_COMMIT_MSG: "No activity available to update"
          COMMIT_NAME: Automated GitHub Activity Readme Update
          TARGET_FILE: README.md
